plugins {
	id 'org.springframework.boot' version '2.5.4'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'com.microsoft.azure.azurewebapp' version '1.1.0'
	id 'java'
}

group = 'com.mdrsolutions'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '8'

repositories {
	maven { url 'https://repo.spring.io/release' }
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'com.google.code.findbugs:jsr305:3.0.2'
	// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-thymeleaf
	//implementation group: 'org.springframework.boot', name: 'spring-boot-starter-thymeleaf', version: '2.5.3'
	//implementation group: 'nz.net.ultraq.thymeleaf', name: 'thymeleaf-layout-dialect', version: '2.5.3'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
	useJUnitPlatform()
}


azurewebapp {
	subscription = '810a4acf-81a7-4410-b32a-85c32940087b'
	resourceGroup = 'SpringBoot-Azure-Group'
	appName = 'SpringBoot-Azure-App'
	pricingTier = 'B1'
	region = 'westus'
	runtime {
		os = 'Linux'
		webContainer = 'Java SE'
		javaVersion = 'Java 8'
	}
	appSettings {
		SPRING_PROFILES_ACTIVE = 'dev,azure'
	}
	auth {
		type = 'azure_cli' // support azure_cli, oauth2, device_code and service_principal
	}
}